services:
  bd:
    container_name: historia-internet-bd
    image: mysql:8.0
    networks:
      - historia-internet
    environment:
      MYSQL_DATABASE: historia_local
      MYSQL_USER: historia
      MYSQL_PASSWORD: clave
      MYSQL_ROOT_PASSWORD: clave
    volumes:
      - ./basededatos:/var/lib/mysql

  wordpress:
    container_name: historia-internet-wp
    depends_on:
      - bd
    image: wordpress
    ports:
      - 4040:80
    networks:
      - historia-internet
    environment:
      WORDPRESS_DB_HOST: bd
      WORDPRESS_DB_USER: historia
      WORDPRESS_DB_PASSWORD: clave
      WORDPRESS_DB_NAME: historia_local
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
    volumes:
      - ./wordpress:/var/www/html
      - ./extensiones/enflujo-historia-internet-config:/var/www/html/wp-content/plugins/enflujo-historia-internet-config
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  admin:
    container_name: historia-internet-admin
    image: phpmyadmin
    depends_on:
      - bd
    ports:
      - '8090:80'
    environment:
      PMA_HOST: bd
      MYSQL_ROOT_PASSWORD: clave
    networks:
      - historia-internet

networks:
  historia-internet:
